name: Update Helm Values with Image Tag

on:
  workflow_run:
    workflows: ["Build & Push Docker Image to ACR"]
    types: [completed]
    branches: [main]

  push:
    branches: [main]
    paths:
      - ".github/workflows/helm-image-update.yaml"
      
permissions:
  contents: write
  actions: read

env:
  VALUES_FILE: password-app/values.yaml

jobs:
  update-helm:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:

      # - name: Download image metadata from build workflow
      #   uses: actions/download-artifact@v4
      #   with:
      #     name: image-metadata
      #     run-id: 
      - name: Checkout source
        uses: actions/checkout@v6
        
      - name: Download image metadata artifact
        env:
           GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            gh run download ${{ github.event.workflow_run.id }} -n image-metadata

      - name: Read metadata
        id: meta
        run: |
          HASH=$(grep '^hash=' image-metadata.txt | cut -d= -f2)
          BUILT=$(grep '^built=' image-metadata.txt | cut -d= -f2)
          echo "hash=$HASH" >> $GITHUB_OUTPUT
          echo "built=$BUILT" >> $GITHUB_OUTPUT

      # Skip entire job if no new image
      - name: Stop if no new image built
        if: ${{ steps.meta.outputs.built == 'true' }}
        run: |
          echo "No new image built — skipping Helm update"
          exit 0

      - name: Checkout helm-update branch
        if: ${{ steps.meta.outputs.built == 'true' }}
        uses: actions/checkout@v6
        with:
          ref: helm-update

      - name: Update values.yaml with hash tag
        if: ${{ steps.meta.outputs.built == 'true' }}
        run: |
          TAG=${{ steps.meta.outputs.hash }}
          sed -i 's|tag: .*|tag: '"$TAG"'|g' $VALUES_FILE

      - name: Commit changes to helm-update branch
        if: ${{ steps.meta.outputs.built == 'true' }}
        run: |
          git config user.name "gha-helm-iamge-update"
          git config user.email "actions@github.com"

          git add $VALUES_FILE
          git commit -m "chore: update image tag to $TAG" || echo "No changes"

          git push origin helm-update

      - name: Create PR helm-update → main
        if: ${{ steps.meta.outputs.built == 'true' }}
        env: 
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            if gh pr list --head helm-update --base main --json number --jq 'length' | grep -q '^0$'; then
            gh pr create \
              --title "Update image tag to $TAG" \
              --body "Auto update Helm image tag to $TAG after image build." \
              --base main \
              --head helm-update
            echo "PR created"
            else
              echo "PR already exists"
            fi
