name: Build & Push Docker Image to ACR

on:
  push:
    branches: [main]
    paths:
      - "app/**"
      - "docker/Dockerfile"
      - ".github/workflows/image-build-push.yaml"

permissions:
  id-token: write
  contents: read
  security-events: write

env:
  ACR_NAME: passwordapp
  IMAGE_NAME: passwordapp
  
jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v6

      # Azure OIDC login (federated)
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.DOCKER_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # Login Docker to ACR using Azure identity
      - name: ACR Login
        run: az acr login --name $ACR_NAME

      # setting up buildx for caching the image.  
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3 

      # Compute Docker content hash (app + Dockerfile)
      - name: Compute Docker context hash
        id: dockerhash
        run: |
          HASH=$(git ls-files app docker | xargs sha1sum | sha1sum | cut -c1-5)
          echo "hash=$HASH" >> $GITHUB_OUTPUT
      
      # Check if this image already exists in ACR
      - name: Check if tag exists in ACR
        id: acrcheck
        run: |
          if az acr repository show-tags --name $ACR_NAME --repository $IMAGE_NAME \
             --query "[?@=='${{ steps.dockerhash.outputs.hash }}']" \
              -o tsv | grep -q .; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      # Build & push only if new Docker content
      - name: Build & Push image
        if: ${{ steps.acrcheck.outputs.exists == 'false' }}
        uses: docker/build-push-action@v6
        with:
          context: app
          file: docker/Dockerfile
          push: false
          load: true
          tags: |
            ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ steps.dockerhash.outputs.hash }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

     # if skipped
      - name: Image already exists
        if: ${{ steps.acrcheck.outputs.exists == 'true' }}
        run: echo "Docker image unchanged — build skipped"

      - name: Pull existing image
        if: steps.acrcheck.outputs.exists == 'true'
        run: docker pull $ACR_NAME.azurecr.io/$IMAGE_NAME:${{ steps.dockerhash.outputs.hash }}
      
      # Scan EXISTING image (ACR)
      - name: Scan existing image with Trivy
        if: steps.acrcheck.outputs.exists == 'true'
        continue-on-error: true
        id: failimagescan
        uses: aquasecurity/trivy-action@0.34.0
        with:
          image-ref: ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ steps.dockerhash.outputs.hash }}
          format: table
          exit-code: 0
          severity: CRITICAL,HIGH
          ignore-unfixed: true

      # Scan NEW image    
      - name: Scan new image with Trivy
        if: steps.acrcheck.outputs.exists == 'false'
        id: passimagescan
        continue-on-error: true
        uses: aquasecurity/trivy-action@0.34.0
        with:
          image-ref: ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ steps.dockerhash.outputs.hash }}
          format: table
          exit-code: 0
          severity: CRITICAL,HIGH
          ignore-unfixed: true
    
      # Push only if NEW + scan passed
      - name: Push image to ACR
        if: steps.acrcheck.outputs.exists == 'false' && steps.passimagescan.outcome == 'success'
        uses: docker/build-push-action@v6
        with:
          context: app
          file: docker/Dockerfile
          push: true
          tags: ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ steps.dockerhash.outputs.hash }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Export image metadata
        if: steps.acrcheck.outputs.exists == 'false' && steps.passimagescan.outcome == 'success'
        run: |
            HASH=${{ steps.dockerhash.outputs.hash }}
            EXISTS=${{ steps.acrcheck.outputs.exists }}

            if [ "$EXISTS" = "false" ]; then
              BUILT=true
            else
              BUILT=false
            fi

            echo "hash=$HASH" > image-metadata.txt
            echo "built=$BUILT" >> image-metadata.txt

      - name: Upload image metadata
        if: steps.acrcheck.outputs.exists == 'false' && steps.passimagescan.outcome == 'success'
        uses: actions/upload-artifact@v4
        with:
          name: image-metadata
          path: image-metadata.txt