name: Build & Push Docker Image to ACR

on:
  push:
    branches: [main]
    paths:
      - "app/**"
      - "docker/Dockerfile"
      - ".github/workflows/image-build-push.yaml"

permissions:
  id-token: write
  contents: read
  #security-events: write

env:
  ACR_NAME: passwordapp
  IMAGE_NAME: passwordapp
  TAG: ""

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v6

      # Azure OIDC login (federated)
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.DOCKER_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # Login Docker to ACR using Azure identity
      - name: ACR Login
        run: az acr login --name $ACR_NAME

      # Short SHA tag (5 chars)
      - name: Set image tag
        id: image
        run: echo "TAG=${GITHUB_SHA::5}" >> $GITHUB_ENV

      - name: Build image
        uses: docker/build-push-action@v6
        with:
          context: app
          file: docker/Dockerfile
          push: true
          tags: ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ env.TAG }}
     
      